# Generated by Django 3.0.3 on 2020-03-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare_app', '0002_auto_20200321_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='skincare_app.Tag'),
        ),
    ]
